# Generated by Django 5.2 on 2025-05-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    def crear_rol_usuario_por_defecto(apps, schema_editor):
        RolUsuario = apps.get_model('app', 'RolUsuario')
        if not RolUsuario.objects.filter(nombre='usuario').exists():
            RolUsuario.objects.create(nombre='usuario')

    dependencies = [
        ('app', '0003_alter_itemcarrito_cantidad_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_rol_usuario_por_defecto),
    ]
